export const CALCULATE_PIPE_SIZE = "CALCULATE_PIPE_SIZE";
export const ON_PIPE_PARAMS_CHANGE = "ON_PIPE_PARAMS_CHANGE";
export const ON_FLUID_COND_CHANGE = "ON_FLUID_COND_CHANGE";
export const ON_DOCUMENTATION_CHANGE = "ON_DOCUMENTATION_CHANGE";
export const GO_BACK_TO_HOME = "GO_BACK_TO_HOME";
